

all: fish_compet properly_nested

fish_compet: fish_compet.cpp
	g++ fish_compet.cpp -o fish_compet --std=c++11

properly_nested: properly_nested.cpp
	g++ properly_nested.cpp -o properly_nested --std=c++11

.PHONY: all clean
