

all: allocate_families weeks_in_hawaii

allocate_families: allocate_families.cpp
	g++ allocate_families.cpp -o allocate_families --std=c++11

weeks_in_hawaii: weeks_in_hawaii.cpp
	g++ weeks_in_hawaii.cpp -o weeks_in_hawaii --std=c++11

.PHONY: all clean
