
min_split_diff: min_split_diff.cpp
	g++ min_split_diff.cpp -o minimum --std=c++11

missing_element: missing_element.cpp
	g++ missing_element.cpp -o missing --std=c++11

odd_occur_array: odd_occur_array.cpp 
	g++ odd_occur_array.cpp -o occur --std=c++11


