
word_machine: word_machine.cpp
	g++ word_machine.cpp -o word_machine --std=c++11

visible: binary_tree.h visible_nodes_bin_tree.cpp
	g++ visible_nodes_bin_tree.cpp binary_tree.h -o visible --std=c++11
